package com.bonvoyage.designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Landpage extends VerticalLayout {
	protected VerticalLayout topLayout;
	protected Image mainLogo;
	protected Label titleLable;
	protected VerticalLayout midLayout;
	protected HorizontalSplitPanel midSplitLayout;
	protected VerticalLayout leftSplitVertical;
	protected Label userLabel;
	protected Image userLogo;
	protected Label historyLabel;
	protected Table userHistory;
	protected VerticalLayout rightSplitVertical;
	protected HorizontalLayout buttonsLayout;
	protected Button offerRideBtn;
	protected Button searchRideBtn;
	protected VerticalLayout bottomLayout;

	public Landpage() {
		Design.read(this);
	}
}
