package com.bonvoyage.designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class OfferThirdStepDesign extends VerticalLayout {
	protected Label titleLabel;
	protected Label subtitleLabel;
	protected HorizontalLayout smokerLayout;
	protected Label smokerLabel;
	protected OptionGroup smokerSelection;
	protected HorizontalLayout handicapLayout;
	protected Label handicapLabel;
	protected OptionGroup handicapSelection;
	protected HorizontalLayout animalLayout;
	protected Label animalLabel;
	protected OptionGroup animalSelection;
	protected HorizontalLayout luggageLayout;
	protected Label luggageLabel;
	protected OptionGroup luggageSelection;

	public OfferThirdStepDesign() {
		Design.read(this);
	}
}
