package com.bonvojage.designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class HistorySubWindowDesign extends VerticalLayout {
	protected Label subWindTitle;
	protected HorizontalLayout bottomLayout;
	protected VerticalLayout labelLayout;
	protected Label dateLabel;
	protected Label fromLabel;
	protected Label toLabel;
	protected Label scoreLabel;
	protected VerticalLayout labelValueLayout;
	protected Label dateLabelValue;
	protected Label fromLabelValue;
	protected Label toLabelValue;
	protected Label scoreLabelValue;
	protected VerticalLayout rightmostLayout;

	public HistorySubWindowDesign() {
		Design.read(this);
	}
}
