package com.bonvojage.designs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class OfferSecondStepDesign extends VerticalLayout {
	protected Label titleLabel;
	protected Label subtitleLabel;
	protected Label seatsNumberLabel;
	protected OptionGroup seatsNumberSelection;
	protected Label babyNumberLabel;
	protected OptionGroup babyNumberSelection;
	protected Label childrenNumberLabel;
	protected OptionGroup childrenNumberSelection;

	public OfferSecondStepDesign() {
		Design.read(this);
	}
}
